language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assemble