language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-26

before_script:
  - chmod +x gradlew

script:
  - echo "This branch is $TRAVIS_BRANCH"
  - ./gradlew assemble